Document: pybal
Title: Debian pybal Manual
Author: <insert document author here>
Abstract: This manual describes what pybal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pybal/pybal.sgml.gz

Format: postscript
Files: /usr/share/doc/pybal/pybal.ps.gz

Format: text
Files: /usr/share/doc/pybal/pybal.text.gz

Format: HTML
Index: /usr/share/doc/pybal/html/index.html
Files: /usr/share/doc/pybal/html/*.html

  
